#!/bin/sh

riverctl spawn "zsh .config/river/xdg-portal.sh"

riverctl map normal Super Return spawn kitty
riverctl map normal Super D spawn fuzzel

riverctl map normal Super W close

# Swap to normal lockscreen later
riverctl map normal Super L spawn hyprlock

riverctl map normal None Print spawn "grim - | wl-copy"
riverctl map normal Super Print spawn "zsh ~/.config/scripts/screenshot-slurp.sh"

riverctl map normal Super V spawn "cliphist list | fuzzel -d | cliphist decode | wl-copy"

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Up focus-view up
riverctl map normal Super Down focus-view down
riverctl map normal Super Right focus-view right
riverctl map normal Super Left focus-view left

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Up swap up
riverctl map normal Super+Shift Down swap down
riverctl map normal Super+Shift Right swap right
riverctl map normal Super+Shift Left swap left

# Super+Period and Super+Comma to focus the next/previous output
# riverctl map normal Super Period focus-output next
# riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal Super+Shift Period send-to-output next
# riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super F zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super+Shift F toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
# riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
# riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-source-mute @DEFAULT_SOURCE@ 1'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-source-mute @DEFAULT_SOURCE@ 0'
done

# My bindings

# Set background and border color
riverctl border-width 0
# riverctl background-color 0x002b36
# riverctl border-color-focused 0x93a1a1
# riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 25 660
riverctl keyboard-layout -options "grp:win_space_toggle" us,ru

# Mouse
riverctl input * accel-profile flat
riverctl input * pointer-accel 0.0

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout bsp-layout
# rivertile -view-padding 4 -outer-padding 4 &
river-bsp-layout --inner-gap 4 --outer-gap 4 &

# My settings
riverctl focus-follows-cursor normal
riverctl xcursor-theme Bibata-Modern-Ice 24

# Autoexec
riverctl spawn waybar
riverctl spawn "swaybg -i ~/.config/backgrounds/finalizer.png"
riverctl spawn mako
# riverctl spawn dunst
# remove later
riverctl spawn hypridle
riverctl spawn "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
riverctl spawn "cliphist wipe"
riverctl spawn "wl-paste --watch cliphist store"
riverctl spawn nekoray
riverctl spawn "wayneko --layer top"
# riverctl spawn "~/.config/sway/xdg-desktop.sh"
